-- V1: user accounts. Every person who signs in has exactly one row here.
-- Role-specific details (provider type, patient type, facility, HMO) live in
-- their own tables in later phases and point back to users.id.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(100),                 -- NULL until they use their set-password link
    full_name       VARCHAR(150) NOT NULL,
    phone_number    VARCHAR(30),
    role            VARCHAR(40)  NOT NULL,
    location_area   VARCHAR(100),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_lower CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN (
        'SUPER_ADMIN', 'ADMIN',
        'FINANCE_MANAGER', 'CUSTOMER_CARE', 'RELATIONSHIP_MANAGER',
        'CNO_MEDICAL_DIRECTOR', 'CNO', 'CHIEF_MEDICAL_OFFICER',
        'HEAD_OF_CLINICAL_OPERATIONS', 'NURSING_SUPERVISOR',
        'SERVICE_PROVIDER', 'CLINICAL_PERSONNEL', 'LAB_SCIENTIST', 'PHARMACIST',
        'HOSPITAL_ADMIN', 'PHARMACY_ADMIN', 'LAB_ADMIN',
        'PATIENT', 'HMO'
    ))
);

CREATE INDEX ix_users_role ON users (role);

-- Supabase exposes the public schema through its Data API. Row Level Security
-- with no policies blocks that route completely; the backend connects as the
-- table owner, which isn't affected.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
