-- V2: sign-in tokens. Only SHA-256 hashes are stored, never the raw tokens,
-- so a database leak can't be used to sign in or reset a password.

-- Refresh tokens (the dh_refresh cookie). Each sign-in starts a "family";
-- every refresh rotates to a new token in the same family. If a rotated-out
-- token is used again, the whole family is revoked.
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL,
    family_id   UUID         NOT NULL,
    remember    BOOLEAN      NOT NULL DEFAULT FALSE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    rotated_at  TIMESTAMPTZ,              -- replaced by a newer token
    revoked_at  TIMESTAMPTZ,              -- signed out, password changed, or reuse detected
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_tokens_family  ON refresh_tokens (family_id);
CREATE INDEX ix_refresh_tokens_user    ON refresh_tokens (user_id);
CREATE INDEX ix_refresh_tokens_expires ON refresh_tokens (expires_at);

-- Single-use links: SET (new account, /set-password) and RESET (/reset-password).
CREATE TABLE password_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL,
    purpose     VARCHAR(10)  NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_password_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_password_tokens_purpose CHECK (purpose IN ('SET', 'RESET'))
);
CREATE INDEX ix_password_tokens_user    ON password_tokens (user_id);
CREATE INDEX ix_password_tokens_expires ON password_tokens (expires_at);

ALTER TABLE refresh_tokens  ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_tokens ENABLE ROW LEVEL SECURITY;
