-- V3: shared services used by every portal.

-- In-app notifications (the bell in every dashboard).
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title       VARCHAR(150)  NOT NULL,
    message     TEXT,
    link        VARCHAR(300),             -- a frontend path, e.g. /admin/care-requests
    read_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_notifications_user_created ON notifications (user_id, created_at DESC);

-- Who did what, and when. Names and roles are copied in so the log still
-- reads correctly if a user is renamed or removed.
CREATE TABLE activity_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    actor_name   VARCHAR(150),
    actor_role   VARCHAR(40),
    action       VARCHAR(60)   NOT NULL,   -- e.g. SIGNED_IN, USER_CREATED
    description  TEXT,
    entity_type  VARCHAR(60),              -- e.g. CARE_REQUEST
    entity_id    BIGINT,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_activity_created ON activity_log (created_at DESC);
CREATE INDEX ix_activity_actor   ON activity_log (actor_id, created_at DESC);
CREATE INDEX ix_activity_role    ON activity_log (actor_role, created_at DESC);

-- Files stored in Cloudinary. Medical documents are uploaded as "private":
-- they can only be opened through a short-lived signed link from the backend.
CREATE TABLE stored_files (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id       BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    original_name  VARCHAR(255)  NOT NULL,
    content_type   VARCHAR(120),
    size_bytes     BIGINT        NOT NULL,
    public_id      VARCHAR(255)  NOT NULL,
    resource_type  VARCHAR(10)   NOT NULL,   -- image | raw
    delivery_type  VARCHAR(10)   NOT NULL,   -- upload (public) | private
    secure_url     VARCHAR(500),             -- only for public files
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_stored_files_public_id UNIQUE (public_id),
    CONSTRAINT ck_stored_files_delivery CHECK (delivery_type IN ('upload', 'private'))
);
CREATE INDEX ix_stored_files_owner ON stored_files (owner_id);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log  ENABLE ROW LEVEL SECURITY;
ALTER TABLE stored_files  ENABLE ROW LEVEL SECURITY;
