-- V4: what the public forms create.

-- Book Care (public site) and phone requests logged by Customer Care.
CREATE TABLE care_requests (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id              BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    full_name               VARCHAR(150)  NOT NULL,
    email                   VARCHAR(255)  NOT NULL,
    phone_number            VARCHAR(30)   NOT NULL,
    address                 VARCHAR(300),
    location_area           VARCHAR(60),
    service_needed          VARCHAR(100)  NOT NULL,
    description             TEXT,
    preferred_contact_time  VARCHAR(40),
    status                  VARCHAR(30)   NOT NULL DEFAULT 'NEW',
    source                  VARCHAR(20)   NOT NULL DEFAULT 'WEBSITE',   -- WEBSITE | CUSTOMER_CARE | PORTAL
    created_by_id           BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX ix_care_requests_status  ON care_requests (status, created_at DESC);
CREATE INDEX ix_care_requests_patient ON care_requests (patient_id, created_at DESC);

-- Care providers (nurses, physios, aides...). A row starts as a PENDING
-- application from the public "Apply" form; Admin approval creates the
-- SERVICE_PROVIDER user and fills user_id.
CREATE TABLE providers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT        UNIQUE REFERENCES users (id) ON DELETE SET NULL,
    status                  VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    full_name               VARCHAR(150)  NOT NULL,
    email                   VARCHAR(255)  NOT NULL,
    phone_number            VARCHAR(30)   NOT NULL,
    address                 VARCHAR(300)  NOT NULL,
    gender                  VARCHAR(30),
    service_type            VARCHAR(80)   NOT NULL,   -- as chosen on the form, e.g. "Registered Nurse (RN)"
    provider_type           VARCHAR(40),              -- set by Admin on approval, e.g. REGISTERED_NURSE
    years_of_experience     VARCHAR(40)   NOT NULL,
    qualification           VARCHAR(60),
    employment_status       VARCHAR(60),
    specialisations         TEXT,
    professional_summary    TEXT,
    availability_type       VARCHAR(30)   NOT NULL,
    preferred_hours         VARCHAR(200),
    location_area           VARCHAR(60),
    start_date              VARCHAR(40),
    additional_info         TEXT,
    ref1_full_name          VARCHAR(150),
    ref1_relationship       VARCHAR(80),
    ref1_phone              VARCHAR(30),
    ref1_email              VARCHAR(255),
    ref2_full_name          VARCHAR(150),
    ref2_relationship       VARCHAR(80),
    ref2_phone              VARCHAR(30),
    ref2_email              VARCHAR(255),
    cv_file_id              BIGINT        NOT NULL REFERENCES stored_files (id),
    certificate_file_id     BIGINT        REFERENCES stored_files (id),
    government_id_file_id   BIGINT        REFERENCES stored_files (id),
    license_file_id         BIGINT        REFERENCES stored_files (id),
    reviewed_by_id          BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    reviewed_at             TIMESTAMPTZ,
    review_note             TEXT,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_providers_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
);
CREATE INDEX ix_providers_status ON providers (status, created_at DESC);
CREATE INDEX ix_providers_email  ON providers (email);

-- HMO client companies. Starts as a PENDING application from the public HMO
-- form (or an RM onboarding); Admin approval creates the HMO user.
CREATE TABLE hmo_organisations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id     BIGINT        UNIQUE REFERENCES users (id) ON DELETE SET NULL,
    status            VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    company_name      VARCHAR(200)  NOT NULL,
    company_size      VARCHAR(30)   NOT NULL,
    email             VARCHAR(255)  NOT NULL,
    phone_number      VARCHAR(30)   NOT NULL,
    company_address   VARCHAR(300)  NOT NULL,
    hr_contact_name   VARCHAR(150),
    industry          VARCHAR(100),
    start_date        DATE,
    created_by        VARCHAR(30)   NOT NULL DEFAULT 'PUBLIC',   -- PUBLIC | RELATIONSHIP_MANAGER
    reviewed_by_id    BIGINT        REFERENCES users (id) ON DELETE SET NULL,
    reviewed_at       TIMESTAMPTZ,
    review_note       TEXT,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_hmo_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED'))
);
CREATE INDEX ix_hmo_status ON hmo_organisations (status, created_at DESC);
CREATE INDEX ix_hmo_email  ON hmo_organisations (email);
CREATE INDEX ix_hmo_name   ON hmo_organisations (lower(company_name));

ALTER TABLE care_requests     ENABLE ROW LEVEL SECURITY;
ALTER TABLE providers         ENABLE ROW LEVEL SECURITY;
ALTER TABLE hmo_organisations ENABLE ROW LEVEL SECURITY;
